# Problem 1

In [ ]:
pip insall nump

In [10]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris= np.random.randint(0,11,size=(5,))
print(matris)
# 3 - matris'in boyutunu öğrenin
print(matris.shape)
# 4 - matris'i yeniden boyutlandırın
multi= matris.reshape(5,1)
print(multi)
# 5 - matris'in boyut sayısını öğrenin
print(matris.ndim)

[ 5  1  6 10 10]
(5,)
[[ 5]
 [ 1]
 [ 6]
 [10]
 [10]]
1


# Problem 2

In [ ]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
import numpy as np
matris= np.arange(1,11,2).reshape(2,3)
print(matris)
# 2 - Oluşturduğunuz matrisi parçalayın
parcala=np.split(matris,[1,2])
print(parcala)
# 3 - Parçalanmış matrisleri birleştirin
birlestir=np.concatenate(parcala)
print(birlestir)

# Problem 3

In [17]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
sayilar= np.arange(5,101,2)
matris=np.random.choice(sayilar,size=(2,5))
# 2 - matris'in özelliklerini inceleyin
print("Matris:",matris)
print("Boyut:",matris.shape)
print("Boyut Sayisi:",matris.ndim)
print("Veri Tipi:",matris.dtype)

Matris: [[ 9 55 15 21 63]
 [81 29 49 97 57]]
Boyut: (2, 5)
Boyut Sayisi: 2
Veri Tipi: int32
